CREATE TABLE "SYSTEM"."DRIVERS"
(	"ID" NUMBER(10,0) NOT NULL ENABLE,
     "ADDRESS" VARCHAR2(255 CHAR),
     "DRIVE_LEVEL" VARCHAR2(255 CHAR),
     "FULLNAME" VARCHAR2(255 CHAR),
     "PHONE_NUMBER" VARCHAR2(255 CHAR),
     PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


CREATE TABLE "SYSTEM"."LINE"
(	"ID" NUMBER(10,0) NOT NULL ENABLE,
     "DISTANCE" FLOAT(126) NOT NULL ENABLE,
     "STOP_POINT" NUMBER(10,0),
     PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


CREATE TABLE "SYSTEM"."ASSIGNMENT"
(	"TURN_NUMBER" NUMBER(10,0),
     "LINE_ID" NUMBER(10,0) NOT NULL ENABLE,
     "DRIVER_ID" NUMBER(10,0) NOT NULL ENABLE,
     PRIMARY KEY ("LINE_ID", "DRIVER_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE,
     CONSTRAINT "FKHXXO0TCX2KDQ6C8M42CS29HNR" FOREIGN KEY ("LINE_ID")
         REFERENCES "SYSTEM"."LINE" ("ID") ENABLE,
     CONSTRAINT "FK8JLX0MC7R09SH6L99L5E06V3E" FOREIGN KEY ("DRIVER_ID")
         REFERENCES "SYSTEM"."DRIVERS" ("ID") ENABLE,
     CONSTRAINT "FK6M01I7O8EGNP2GOK2XXOOTBNF" FOREIGN KEY ("DRIVER_ID")
         REFERENCES "SYSTEM"."DRIVER" ("ID") ENABLE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;



CREATE TABLE "SYSTEM"."BUS_LINE"
(	"ID" NUMBER,
     "DISTANCE" NUMBER NOT NULL ENABLE,
     "BUS_STOP_NUMBER" NUMBER NOT NULL ENABLE,
     PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;